databases:
  - name: django-car-rental-db
    plan: free
    ipAllowList: []

services:
  - type: web
    name: django-car-rental-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile.render
    startCommand: ./render-entrypoint.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: car_rental.settings.render
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: django-car-rental-api.onrender.com
      - key: POSTGRES_DB
        fromDatabase:
          name: django-car-rental-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: django-car-rental-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: django-car-rental-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: django-car-rental-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: django-car-rental-db
          property: port
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        value: your-email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-app-password
      - key: REDIS_URL
        fromService:
          type: redis
          name: django-car-rental-redis
          property: connectionString

  - type: redis
    name: django-car-rental-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all IPs

